trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
#  publishVstsFeed: ''

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      version: 8.x
      performMultiLevelLookup: true
      includePreviewVersions: true # Required for preview versions

  - task: DotNetCoreCLI@2
    displayName: Restore packages
    inputs:
      command: 'restore'
      projects: './GenerativeAI.sln'
      restoreArguments: '-c Release'
      feedsToUse: 'select'
#      vstsFeed: '$(publishVstsFeed)' # A series of numbers and letters

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: 'build'
      projects: './GenerativeAI.sln'
      arguments: '-c $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: Pack for .NET
    inputs:
      command: 'pack'
      packagesToPack: './src/Mscc.GenerativeAI/Mscc.GenerativeAI.csproj'
      nobuild: true
      versioningScheme: 'off'
#  - task: NuGetCommand@2
#    displayName: Pack for .NET
#    inputs:
#      command: pack
#      packagesToPack: './src/Mscc.GenerativeAI/Mscc.GenerativeAI.csproj'
#      packDestination: '$(Build.ArtifactStagingDirectory)'

  - task: DotNetCoreCLI@2
    displayName: Pack for ASP.NET Core
    inputs:
      command: 'pack'
      packagesToPack: './src/Mscc.GenerativeAI.Web/Mscc.GenerativeAI.Web.csproj'
      nobuild: true
      versioningScheme: 'off'

  - task: DotNetCoreCLI@2
    displayName: Pack for .NET using Google Cloud Client Library
    inputs:
      command: 'pack'
      packagesToPack: './src/Mscc.GenerativeAI.Google/Mscc.GenerativeAI.Google.csproj'
      nobuild: true
      versioningScheme: 'off'

#  - task: DotNetCoreCLI@2
#    displayName: Push to Azure DevOps feed
#    inputs:
#      command: 'push'
#      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
#      nuGetFeedType: 'internal'
#      publishVstsFeed: '$(publishVstsFeed)'
  - task: NuGetCommand@2
    displayName: Push to Azure DevOps feed
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '$(publishVstsFeed)'
      allowPackageConflicts: true
