# outline the steps to build a .NET project, pack it as Nuget package and push it to Nuget source feed
steps:
# Build the project
- name: 'gcr.io/cloud-builders/dotnet'
  args: ['build', '-c', 'Release', 'GenerativeAI.sln']
# Pack the NuGet package
- name: 'gcr.io/cloud-builders/dotnet'
  args: ['pack', '-c', 'Release', 'GenerativeAI.sln', '-o', 'output/']
# Push the package to NuGet source feed
- name: 'gcr.io/cloud-builders/dotnet'
  args: ['nuget', 'push', 'output/*.nupkg', '-k', '${_NUGET_API_KEY}', '-s', 'https://api.nuget.org/v3/index.json']

options:
  substitutionOption: 'ALLOW_LOOSE'
substitutions:
  _NUGET_API_KEY: YOUR_NUGET_API_KEY
