name: Create Release

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out latest sources
        uses: actions/checkout@v4
        with:
          fetch-tags: 'true'

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: |
            ## What's changed
            
            ---- 
            **Full Changelog**: https://github.com/mscraftsman/generative-ai/compare/vx.x.x...${{ github.ref_name }}
          draft: false
          prerelease: false
